export default function useStates() {
  const get = async (country) => {
    const states = {
      argentina: [
        "Gran Chaco",
        "Mesopotâmia",
        "Cuyo",
        "Pampas",
        "Litoral",
        "Patagonia",
        "Noroeste argentino",
      ],
      australia: [
        "Nova Gales do Sul",
        "Queensland",
        "Austrália do Sul",
        "Tasmânia",
        "Victoria ",
        "Austrália Ocidental",
      ],
      usa: [
        "AK: Alasca",
        "AL: Alabama",
        "AR: Arkansas",
        "AZ: Arizona",
        "CA: Califórnia",
        "CO: Colorado",
        "CT: Connecticut",
        "DE: Delaware",
        "FL: Flórida",
        "GA: Geórgia",
        "HI: Havaí",
        "IA: Iowa",
        "ID: Idaho",
        "IL: Illinois",
        "IN: Indiana",
        "KS: Kansas",
        "KY: Kentucky",
        "LA: Louisiana",
        "MA: Massachusetts",
        "MD: Maryland",
        "ME: Maine",
        "MI: Michigan",
        "MN: Minnesota",
        "MO: Missouri",
        "MS: Mississippi",
        "MT: Montana",
        "NC: Carolina do Norte",
        "ND: Dakota do Norte",
        "NE: Nebraska",
        "NH: Nova Hampshire",
        "NJ: Nova Jérsei",
        "NM: Novo México",
        "NV: Nevada",
        "NY: Nova Iorque",
        "OH: Ohio",
        "OK: Oklahoma",
        "OR: Oregon",
        "PA: Pensilvânia",
        "RI: Rhode Island",
        "SC: Carolina do Sul",
        "SD: Dakota do Sul",
        "TN: Tennessee",
        "TX: Texas",
        "UT: Utah",
        "VT: Vermont",
        "VA: Virgínia",
        "WA: Washington",
        "WI: Wisconsin",
        "WV: Virgínia Ocidental",
        "WY: Wyoming",
      ],

      portugal: [
        "Aveiro",
        "Beja",
        "Braga",
        "Bragança",
        "Castelo Branco",
        "Coimbra",
        "Évora",
        "Faro",
        "Guarda",
        "Leiria",
        "Lisboa",
        "Portalegre",
        "Porto",
        "Santarém",
        "Setúbal",
        "Viana do Castelo",
        "Vila Real",
        " Viseu ",
      ],
      brasil: [
        "Centro-Oeste",
        "Distrito Federal",
        "Nordeste",
        "Norte",
        "Sul",
        "Sudeste",
      ],
    };

    return states[country];
  };

  return {
    get,
  };
}
